spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRE_URL:localhost}:${POSTGRE_PORT:5432}/course"
    username: ${POSTGRE_USERNAME:user}
    password: ${POSTGRE_PASSWORd:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false